// Generated by CoffeeScript 1.10.0
(function() {
  var Canvas, fs, qr;

  Canvas = require('canvas');

  fs = require('fs');

  qr = require('qr-js');

  module.exports = function(qrContent, headFile, destFile) {
    return fs.readFile(__dirname + '/bk.jpg', function(err, squid) {
      var canvas, ctx, img, img1;
      if (err != null) {
        throw err;
      }
      img = new Canvas.Image;
      img.src = squid;
      canvas = new Canvas(img.width, img.height);
      ctx = canvas.getContext('2d');
      ctx.drawImage(img, 0, 0);
      img1 = qr.image(qrContent);
      ctx.drawImage(img1, 150, 400);
      ctx.save();
      ctx.beginPath();
      ctx.arc(200, 145, 50, 0, 2 * Math.PI);
      ctx.fillStyle = '#e4c5a8';
      ctx.fill();
      ctx.closePath();
      ctx.restore();
      return fs.readFile(__dirname + '/' + headFile, function(err, squid) {
        var img2, out, stream;
        if (err != null) {
          throw err;
        }
        img2 = new Canvas.Image;
        img2.src = squid;
        ctx.save();
        ctx.beginPath();
        ctx.arc(200, 145, 45, 0, 2 * Math.PI);
        ctx.clip();
        ctx.drawImage(img2, 155, 100, 90, 90);
        ctx.restore();
        out = fs.createWriteStream(__dirname + '/' + destFile);
        stream = canvas.pngStream();
        stream.on('data', function(chunk) {
          return out.write(chunk);
        });
        stream.on('error', function(err) {
          throw err;
        });
        return stream.on('end', function() {});
      });
    });
  };

}).call(this);
