// Generated by CoffeeScript 1.10.0
(function() {
  var Canvas, fs, qr;

  Canvas = require('canvas');

  fs = require('fs');

  qr = require('qr-js');

  module.exports = function(qrContent, headFile, destFile) {
    var buf, buf1, canvas, ctx, img, img1, img2, out, stream;
    buf = fs.readFileSync(__dirname + '/bk.jpg');
    img = new Canvas.Image;
    img.src = buf;
    canvas = new Canvas(img.width, img.height);
    ctx = canvas.getContext('2d');
    ctx.drawImage(img, 0, 0);
    img1 = qr.image(qrContent);
    ctx.drawImage(img1, 150, 400);
    ctx.save();
    ctx.beginPath();
    ctx.arc(200, 145, 50, 0, 2 * Math.PI);
    ctx.fillStyle = '#e4c5a8';
    ctx.fill();
    ctx.closePath();
    ctx.restore();
    buf1 = fs.readFileSync(__dirname + '/' + headFile);
    img2 = new Canvas.Image;
    img2.src = buf1;
    ctx.save();
    ctx.beginPath();
    ctx.arc(200, 145, 45, 0, 2 * Math.PI);
    ctx.clip();
    ctx.drawImage(img2, 155, 100, 90, 90);
    ctx.restore();
    out = fs.createWriteStream(__dirname + '/' + destFile);
    stream = canvas.pngStream();
    stream.on('data', function(chunk) {
      return out.write(chunk);
    });
    stream.on('error', function(err) {
      throw err;
    });
    return stream.on('end', function() {});
  };

}).call(this);
